name: Publish API to Production

on:
  workflow_call:
    secrets:
      GH_PACKAGES:
        required: true
  workflow_dispatch:

jobs:
  publish_prod_api:
    if: "!contains(github.event.head_commit.message, 'ci skip')"
    runs-on: ubuntu-latest
    timeout-minutes: 80
    permissions:
      contents: read
      packages: write 
      deployments: write
    steps:
      - uses: actions/checkout@v2
      - name: Setup kernel for react native, increase watchers
        run: echo fs.inotify.max_user_watches=524288 | sudo tee -a /etc/sysctl.conf && sudo sysctl -p

      - name: Start MongoDB
        uses: supercharge/mongodb-github-action@1.3.0
        with:
          mongodb-version: 4.2.8
      
      - name: Build & Tag Docker image
        env:
          REGISTERY_OWNER: implerhq
          DOCKER_NAME: impler/api
          IMAGE_TAG: ${{ github.event.pull_request.head.sha || github.sha }}
        run: |
          docker build -t ghcr.io/$REGISTERY_OWNER/$DOCKER_NAME:$IMAGE_TAG -f apps/api/Dockerfile .
          docker tag ghcr.io/$REGISTERY_OWNER/$DOCKER_NAME:$IMAGE_TAG ghcr.io/$REGISTERY_OWNER/$DOCKER_NAME:latest

      - name: Run Docker container
        env:
          REGISTERY_OWNER: implerhq
          DOCKER_NAME: impler/api
          IMAGE_TAG: ${{ github.event.pull_request.head.sha || github.sha }}
        run: docker run --network=host --name api -dit --env NODE_ENV=test --env JWT_SECRET=impler --env COOKIE_DOMAIN=impler ghcr.io/$REGISTERY_OWNER/$DOCKER_NAME:$IMAGE_TAG
      
      - name: Check application health
        run: docker run --network=host appropriate/curl --retry 10 --retry-delay 5 --retry-connrefused http://localhost:3000/v1/health-check | grep 'ok'

      - name: Log in to GitHub Container Registry
        env:
          GH_ACTOR: implerhq
          GH_PASSWORD: ${{ secrets.GH_PACKAGES }}
        run: echo $GH_PASSWORD | docker login ghcr.io -u $GH_ACTOR --password-stdin
    
      - name: Push Docker image
        env:
          REGISTERY_OWNER: implerhq
          DOCKER_NAME: impler/api
          IMAGE_TAG: ${{ github.event.pull_request.head.sha || github.sha }}
        run: |
          docker push ghcr.io/$REGISTERY_OWNER/$DOCKER_NAME:$IMAGE_TAG
          docker push ghcr.io/$REGISTERY_OWNER/$DOCKER_NAME:latest
          echo "::set-output name=IMAGE::ghcr.io/$REGISTERY_OWNER/$DOCKER_NAME:$IMAGE_TAG"
