name: Publish Packages to NPM Registry

on:
  workflow_call:
    secrets:
      NPM_TOKEN:
        required: true

jobs:
  publish_prod_react:
    if: "!contains(github.event.head_commit.message, 'ci skip')"
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    timeout-minutes: 80
    permissions:
      contents: read
      packages: write 
      deployments: write
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      - name: Setup kernel for react native, increase watchers
        run: echo fs.inotify.max_user_watches=524288 | sudo tee -a /etc/sysctl.conf && sudo sysctl -p
      
      - uses: actions/setup-node@v2
        with:
          node-version: '20.13.1'

      - name: Cache pnpm modules
        uses: actions/cache@v2
        with:
          path: ~/.pnpm-store
          key: ${{ runner.os }}-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-
      
      - uses: pnpm/action-setup@v2.0.1
        env:
          CI: false
        with:
          version: 8.9.0
          run_install: true

      - name: Publish @impler/client package on NPM 📦
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
        working-directory: packages/client
        run: |
          npm config set --workspaces=false --include-workspace-root registry https://registry.npmjs.org/
          npm config set --workspaces=false --include-workspace-root //registry.npmjs.org/:_authToken=$NPM_TOKEN
          npm publish --access public

      - name: Publish @impler/react package on NPM 📦
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
        working-directory: packages/react
        run: |
          npm config set --workspaces=false --include-workspace-root registry https://registry.npmjs.org/
          npm config set --workspaces=false --include-workspace-root //registry.npmjs.org/:_authToken=$NPM_TOKEN
          npm publish --access public

      - name: Publish @impler/angular package on NPM 📦
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
        working-directory: packages/angular
        run: |
          npm config set --workspaces=false --include-workspace-root registry https://registry.npmjs.org/
          npm config set --workspaces=false --include-workspace-root //registry.npmjs.org/:_authToken=$NPM_TOKEN
          npm publish --access public
